CUDA_VISIBLE_DEVICES=0 python main.py \
    --optimizer 'adam' \
    --lr 0.003 \
    --dropout 0.2 \
    --batch_size 256 \
    --epochs 500 \
    --max_traj_len 3 \
    --M 2 \
    --aug_range 0 \
    --attn_heads 32 \
    --num_layers 2 \
    --step_size 40 \
    --lr_decay 0.65 \
    --model_name 'niv' \
    --dataset 'niv' \
    --num_action 48 \
    --num_tasks 5 \
    --img_input_dim 512 \
    --text_input_dim 768 \
    --embed_dim 128 \
    --root_dir 'dataset/niv' \
    --train_json 'dataset/niv/niv_train.json' \
    --valid_json 'dataset/niv/niv_valid.json' \
    --features_dir '/home/wenliang/data/processed_data_niv' \
    --no_action_proj_loss